### ISSUE TITLE
Vertaisarvionti

### ISSUE THREAD

**Issue by TeemuBergman** [ollpu/tiralabra#1]
# Vertaisarviointi

Vertaisarvioitava projekti ladattu 22.4.2021 klo 14.00.

Testattu käyttöjärjestelmissä Windows 10 (1809) ja Ubuntu 18.04.5 LTS.

## Yleistä

- Dokumentaatio on hyvin kattavaa ja helppoa seurata, varsinkin koodin dokumentaatiossa on menty hyvin yksityiskohtaiselle tarkkuudelle metodien toiminnallisuudessa. 

- Yritin suorittaa demoa Ubuntussa readme:ssä annettujen ohjeiden mukaan itse kääntämällä ja se päätyi virheeseen:

  ```
  thread 'main' panicked at 'Failed to run `"pkg-config" "--libs" "--cflags" "alsa"`: No such file or directory (os error 2)', /home/tab/.cargo/registry/src/github.com-1ecc6299db9ec823/alsa-sys-0.3.1/build.rs:13:18
  ```

  Tämä oli erikoista, sillä kyseinen tiedosto kyllä oli tuossa kansiossa olemassa, mutta ehkä sittenkin suoritin sen jotenkin väärällä tavalla?

- Latasin sitten valmiiksi käännetyn binäärin, mutta en saanut sitäkään toimimaan Ubuntun puolella. Tästä olisi ehkä voinut ohjeistaa vielä hieman tarkemmin?

- Windowsin puolella binääri käynnistyi, mutta en saanut äänen perustaajuuden seuraamista toimimaan. Ilmeisesti sovellukselle olisi pitänyt syöttää ääntä äänikortin sisääntulosta ja sitä mahdollisuutta minulla ei tällä kertaa ollut käytettävissä.

- Mielestäni on kuitenkin erittäin hyvä, että sovelluksen lähdekoodi oli konfiguroitu kummallekin käyttöjärjestelmälle sekä binäärit oli käännetyt valmiiksi.

## Koodista

- Koodin kommentoinnin kattavuus on mielestäni hyvällä tasolla ja siitä saa helposti käsityksen eri metodien tarkoituksista.
- Koodi itsessään vaikutti hyvin laadukkaalta, enkä kyennyt "haistamaan" siitä mitään erityistä. Tämä on hyvää referenssiä itselleni, kun en vielä ole saavuttanut vastaavaa tasoa. 5/5!
- Projektin rakenne kansioinnin ja niissä sijaitsevien tiedostojen suhteen vaikuttaa tarkoituksenmukaiselta ja selkeältä.
- Koodin testausta vaikutti olevan riittävästi mukana, jatkuva integraation oli ok ja haarautumakattavuus hyvällä tasolla.

Tästä tulee todella hyvä kun nämä muutamat pienet edellä mainitut puutteet ratkaisee. Onnea jatkoon! :)

**Comment by ollpu** [comment]
Kiitos kattavasta vertaisarvioinnista!

Hyvä tietää, että käyttöohjeissa on parantamisen varaa. Tuli heti mieleen, että Ubuntulla pitäisi asentaa `libasound2-dev`, jotta äänen kuuntelun saa kääntymään. Yritän selvittää mikä binäärin kanssa on ongelmana.

**EDIT:** Binäärin onglema Ubuntulla selvisi tietysti heti, kun yritin sitä ajaa toisella Ubuntulla: se on käännetty liian uusille järjestelmäkirjastoille.
